name: 'Terraform Backend Checker'
description: 'Check existence of tf backend'
inputs:
   terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Terraform Backend
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        grep -Ri "backend \"gcs\"" ./
        RC=$?
        if [ $RC -eq 0 ]; then
          echo "Backend configured, proceeding with jobs..." >> $GITHUB_OUTPUT
        else
          delimiter="$(openssl rand -hex 8)"
          CONF_BACKEND="Backend not configured. Please configure the [backend](https://github.com/optimizely/experimentation-golden-path/blob/main/golden_path/guides/quickstart_guide.md)"
          
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "$CONF_BACKEND" >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

          echo "$summary" >> $GITHUB_STEP_SUMMARY
        fi
    - name: Test
      shell: bash
      run: |
        echo "Test Ran ......."