name: 'Terraform Backend Checker'
description: 'Check existence of tf backend'
inputs:
   terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Terraform Backend
      working-directory: ${{ inputs.terraform_directory }}
      id: backend_check
      shell: bash
      run: |
        grep -Ri "backend \"gcs\"" ./
        RC=$?
        if [ $RC -eq 0 ]; then
          echo "Backend configured, proceeding with jobs..."
          echo "::set-output name=backend_configured::true"
        else
          echo "Backend not configured. Exiting pipeline."
          echo "::set-output name=backend_configured::false"
        fi
    - name: Test
      shell: bash
      if: steps.backend_check.outputs.backend_configured == 'true'
      run: |
        echo "Test Ran ......."