name: 'Terraform Backend Checker'
description: 'Check existence of tf backend'
inputs:
   terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Terraform Backend
      working-directory: ${{ inputs.terraform_directory }}
      id: backend-checker
      shell: bash
      run: |
        if grep -Ri "backend \"gcs\"" ./; then
          echo "Backend Configured..."
        else
          touch failure_summary.txt
          echo "Err!!!"
          echo "Backend not configured. Please configure using this link: https://github.com/optimizely/experimentation-golden-path/blob/main/golden_path/guides/quickstart_guide.md" > failure_summary.txt
          exit 1
        fi
    
    - name: test
      shell: bash
      run: |
        exit 1

    - name: Display Failure Summary
      shell: bash
      if: ${{ failure() && steps.backend-checker.outcome == 'failure' }}
      run: |
        cat failure_summary.txt >> $GITHUB_STEP_SUMMARY