name: 'Terraform Backend Checker'
description: 'Check existence of tf backend'
inputs:
   terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Terraform Backend
      working-directory: ${{ inputs.terraform_directory }}
      id: backend-checker
      shell: bash
      run: |
        grep -Ri "backend \"gcs\"" ./
        RC=$?
        if [ $RC -eq 0 ]; then
          echo "Backend configured, proceeding with jobs..."
        else
          echo "Backend not configured. Please configure using this link: https://github.com/optimizely/experimentation-golden-path/blob/main/golden_path/guides/quickstart_guide.md"
        fi