name: 'Terraform Backend Checker'
description: 'Check existence of tf backend'
inputs:
   terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Terraform Backend
      working-directory: ${{ inputs.terraform_directory }}
      id: backend-checker
      shell: bash
      run: |
        grep -Ri "backend \"gcs\"" ./
        RC=$?
        if [ $RC -eq 0 ]; then
          echo "Backend configured, proceeding with jobs..."
        else
          CONF_BACKEND="Backend not configured. Please configure the [backend](https://github.com/optimizely/experimentation-golden-path/blob/main/golden_path/guides/quickstart_guide.md)"
          echo "::set-output name=summary::$CONF_BACKEND"
        fi
    - name: Test
      shell: bash
      run: |
        echo "Test Ran ......."
    
    - name: Display Summary
      if: failure() # Ensures this step runs regardless of previous steps' success or failure
      shell: bash
      env:
        SUMMARY: ${{ steps.backend-checker.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
