name: Main pipeline
on:
  workflow_dispatch:
  push:

jobs:
  tf-backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/tf-backend-checker/
        with:
          terraform_directory: "."
